name: silent_voices
description: A mobile app for inclusive two-way communication between hearing and deaf individuals.

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  speech_to_text: ^6.6.0
  file_picker: ^6.1.1
  camera: ^0.10.5+2

flutter:
  assets:
    - assets/animations/sign_avatar.json
    - assets/icons/user.png
    - assets/icons/email.png
    - assets/icons/lock.png
    - assets/animations/hello.json
    - assets/illustrations/home_illustration.png
    - assets/icons/instagram.png
    - assets/illustrations/signs.png
    - assets/icons/google.png
    - assets/icons/apple.png
    - assets/icons/facebook.png
    - assets/icons/eyec.png
    - assets/icons/eyeo.png
    - assets/icons/arrow.png
    - assets/illustrations/man.png
    - assets/illustrations/sign to speech.png
    - assets/illustrations/speech to sign.png
    - assets/icons/home.png
    - assets/icons/settings.png
    - assets/icons/profile.png
    - assets/icons/animation_speed.png
    - assets/icons/feedback.png
    - assets/icons/language_type.png
    - assets/icons/language.png
    - assets/icons/voice_type.png
    - assets/icons/dropdown_arrow.png
    - assets/illustrations/logo1.png
    - assets/icons/logo.png
    - assets/animations/globe.json
    - assets/background/bg.png
    - assets/icons/cam.png
    - assets/icons/message.png
    - assets/icons/headphone.png
    - assets/icons/camera.png
    - assets/icons/mike.png
    
  
    