// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk9FBDivMnAJNerVPTiXi6WbQ6c7xr6xI',
    appId: '1:435284912537:web:6b61a6bde265a09c540b08',
    messagingSenderId: '435284912537',
    projectId: 'silent-voices-e8a56',
    authDomain: 'silent-voices-e8a56.firebaseapp.com',
    storageBucket: 'silent-voices-e8a56.firebasestorage.app',
    measurementId: 'G-PMTJ4CG7LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ6fOMr8soYhSIqdW66sV4KYL3-Sp6S88',
    appId: '1:435284912537:android:cc1aff3bb61dcfcf540b08',
    messagingSenderId: '435284912537',
    projectId: 'silent-voices-e8a56',
    storageBucket: 'silent-voices-e8a56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZbRKqZ_4xlUhaJu8ZY7SlGtAjwSkeDgw',
    appId: '1:435284912537:ios:a50695baa83cbdf6540b08',
    messagingSenderId: '435284912537',
    projectId: 'silent-voices-e8a56',
    storageBucket: 'silent-voices-e8a56.firebasestorage.app',
    iosBundleId: 'com.example.silentVoices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZbRKqZ_4xlUhaJu8ZY7SlGtAjwSkeDgw',
    appId: '1:435284912537:ios:a50695baa83cbdf6540b08',
    messagingSenderId: '435284912537',
    projectId: 'silent-voices-e8a56',
    storageBucket: 'silent-voices-e8a56.firebasestorage.app',
    iosBundleId: 'com.example.silentVoices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk9FBDivMnAJNerVPTiXi6WbQ6c7xr6xI',
    appId: '1:435284912537:web:6fe386b6b1d9e26d540b08',
    messagingSenderId: '435284912537',
    projectId: 'silent-voices-e8a56',
    authDomain: 'silent-voices-e8a56.firebaseapp.com',
    storageBucket: 'silent-voices-e8a56.firebasestorage.app',
    measurementId: 'G-9VC9T8G822',
  );
}
